### ISSUE TITLE
Name 'dll' is not defined

### ISSUE THREAD

**Issue by jbehlen2** [maximecharriere/iai-gxipy#2]
Hi,

Thank you for wrapping this code into a Python library! It's very much appreciated. I'm using this library on a raspberry pi (3 model B). I'm getting an error when running:

`NameError: name 'dll' is not defined`

Are you able to point to the proper DLL and advise on where it should be placed?

Thanks!

**Comment by jbehlen2** [comment]
Coming back to this. I didn't actually solve the issue, I just moved to a different platform (Jetson Nano Developer Kit) and the problem did not follow. I'm back on a Pi (PI 5), and I'm having the same issue. Any help here would be appreciated!

**Comment by jbehlen2** [comment]
My apologies, I didn't realize I needed to install the Linux ARM SDK before I installed the Linux ARM Python SDK. All settled! Thanks!

**Comment by maximecharriere** [comment]
Feel free to tell me if you have another issue.

**Comment by dobruyyoba** [comment]
> My apologies, I didn't realize I needed to install the Linux ARM SDK before I installed the Linux ARM Python SDK. All settled! Thanks!

Can you explain what and in which order i need to install files? Do you know can i install all of this from docker?

**Comment by maximecharriere** [comment]
I suggest these documentations:
- [How to download install and run the Linux Galaxy SDK suitable for ARM based hardware such as Raspberry PI or Nvidia Jetson](https://va-imaging.com/blogs/machine-vision-knowledge-center/how-to-install-raspberry-pi-with-daheng-imaging-usb3-machine-vision-camera)
- User manual of your camera ([Download page of manuals](https://va-imaging.com/fr/pages/telechargementsclients#Manuals))

For Docker, I never tried. Maybe the communication between the hardware (camera) and the container will be a pain in the a** to configure.

**Comment by jbehlen2** [comment]
dobruyyoba,

I’d suggest downloading the correct materials from [here](https://en.daheng-imaging.com/list-58-1.html). You’ll need to select the correct options for `Product`, `Host`, and `OS` to get the right downloads. Once you have those downloads look at the READMEs for each before you do anything. They give some good details on installation order, dependencies, and troubleshooting common issues.

I have not tried this from Docker. But, I assume you could either do the same process once your container is running, or write a script to handle it for you on creation of the container. Let me know how it goes. I’d be interested to know as I’ll be dockerizing my repo here shortly.

Hope that helps!
